### ISSUE TITLE
NKに格納されている値によって作成するアイテムを変える

### ISSUE THREAD

**Issue by Sakaki-Aruka** [Sakaki-Aruka/custom-crafter#63]
NKの値で作成するアイテムを変える。

ex)
```
result-override:
  "0":
    term: $store_1+$store_2==50
    result: enchanted_golden_apple
```
